# Generated by Django 5.0.6 on 2024-05-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Action', 'Action'), ('Puzzle', 'Puzzle')], max_length=200)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
